let cache={token:'',expires:0};
const arr=v=>Array.isArray(v)?v:[];
const ready=e=>e.FEISHU_APP_ID&&e.FEISHU_APP_SECRET&&e.FEISHU_APP_TOKEN;
async function token(e){if(cache.token&&Date.now()<cache.expires)return cache.token;const r=await fetch('https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({app_id:e.FEISHU_APP_ID,app_secret:e.FEISHU_APP_SECRET})}),d=await r.json();if(d.code)throw Error(d.msg||'飞书鉴权失败');cache={token:d.tenant_access_token,expires:Date.now()+(d.expire-120)*1000};return cache.token}
async function request(e,path,options={}){const r=await fetch(`https://open.feishu.cn/open-apis${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token(e)}`,...options.headers}}),d=await r.json();if(d.code)throw Error(d.msg||'飞书请求失败');return d.data}
export async function createRecord(e,t,fields){if(!ready(e))return {mock:true};return request(e,`/bitable/v1/apps/${e.FEISHU_APP_TOKEN}/tables/${t}/records`,{method:'POST',body:JSON.stringify({fields})})}
const update=(e,t,id,fields)=>request(e,`/bitable/v1/apps/${e.FEISHU_APP_TOKEN}/tables/${t}/records/${id}`,{method:'PUT',body:JSON.stringify({fields})});
async function findCustomer(e,phone){if(!ready(e))return null;const d=await request(e,`/bitable/v1/apps/${e.FEISHU_APP_TOKEN}/tables/${e.FEISHU_CUSTOMER_TABLE_ID}/records/search`,{method:'POST',body:JSON.stringify({filter:{conjunction:'and',conditions:[{field_name:'手机号',operator:'is',value:[phone]}]},page_size:1})});return d.items?.[0]||null}
export async function upsertCustomer(e,phone,fields={}){if(!ready(e))return {mock:true};const x=await findCustomer(e,phone),merged={'手机号':phone,...fields};return x?update(e,e.FEISHU_CUSTOMER_TABLE_ID,x.record_id,merged):createRecord(e,e.FEISHU_CUSTOMER_TABLE_ID,merged)}
const base=a=>({'企业所属行业':arr(a.F01),'主营行业':a.F01_primary||a.F01?.[0]||'','其他行业说明':a.F01_other||'','主要业务模式':arr(a.F02),'其他业务模式说明':a.F02_other||'','当前主要经营地':arr(a.F03),'当前经营阶段':a.F04||'','企业经营时间':a.F05||'','企业规模':a.F12||''});
const labels={compliance:['整体可行','基本可行','建议核验','需要专项核验'],business:['基础扎实','基础稳定','正在形成','仍在准备'],crossBorder:['需求明确','已有需求','正在形成','尚不明确'],hkValue:['价值明确','具备价值','值得验证','需要确认']};
const state=(k,n,m)=>labels[k][n/m>=.8?0:n/m>=.6?1:n/m>=.4?2:3];
const issue={'公司秘书或注册地址':'确认公司秘书和注册地址状态','商业登记或周年申报':'优先核验商业登记和周年申报','做账及会计记录':'尽快整理会计记录','审计':'确认审计安排','税务申报':'优先确认税务申报状态','银行账户或跨境收付款':'完善账户及收付款安排','香港雇员或强积金':'核验雇佣及强积金事项','行业牌照或许可':'核验业务是否涉及牌照要求','内地与香港公司之间的合同或资金安排':'梳理境内外主体关系','整体情况不太清楚':'先核清公司的基础状态'};
const id=p=>`${p}${new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format().replace(/\D/g,'')}${String(Math.random()*100|0).padStart(2,'0')}`;
export async function saveAssessment(e,phone,r){if(!ready(e))return {mock:true};const a=r.answers||{},common={'手机号':phone,...base(a)};let saved;
 if(r.type==='pre-hk'){const d=r.dimensions;if(d.compliance+d.business+d.crossBorder+d.hkValue!==r.score)throw Error('评估总分与四维得分不一致');saved=await createRecord(e,e.FEISHU_PRE_HK_TABLE_ID,{...common,'赴港评估ID':id('FGA'),'年度海外收入':a.F06||'','当前客户所在地区':arr(a.F07),'当前收付款币种':arr(a.F08),'当前跨境业务难点':arr(a.F09),'赴港主要目的':arr(a.F10),'赴港首要目的':a.F10_primary||a.F10?.[0]||'','其他赴港目的说明':a.F10_other||'','当前赴港推进状态':a.F11||'','核心知识产权类型':arr(a.IP01),'评估结论':r.conclusion,'评估总分':r.score,'行业及合规实际得分':d.compliance,'企业业务基础实际得分':d.business,'跨境业务需求实际得分':d.crossBorder,'香港发展价值实际得分':d.hkValue,'行业及合规可行性':state('compliance',d.compliance,25),'企业业务基础状态':state('business',d.business,20),'跨境业务需求状态':state('crossBorder',d.crossBorder,20),'香港发展价值状态':state('hkValue',d.hkValue,35),'业务特点':arr(r.features).join('\n'),'需要进一步确认':arr(r.confirmations).join('\n'),'需要特别关注':arr(r.risks).join('\n'),'初步公司主定位':r.position||'','初步公司辅助定位':r.auxiliaryPosition||'','初步架构方向':r.architecture||'','架构附加提示':r.architectureHint||''})}
 else{const items=arr(r.issues).map(x=>issue[x]).filter(Boolean);if(a.HK05==='已经开户但使用中遇到问题')items.push('优先处理账户使用问题');if(arr(a.HK03).includes('海外签约及跨境收付款')&&a.HK05==='尚未申请开户')items.push('完善跨境收付款能力');saved=await createRecord(e,e.FEISHU_IN_HK_TABLE_ID,{...common,'在港评估ID':id('IGA'),'香港公司当前状态':a.HK01||'','香港公司成立时间':a.HK02||'','香港公司主要作用':arr(a.HK03),'香港公司主要作用（首要）':a.HK03_primary||a.HK03?.[0]||'','其他香港公司作用说明':a.HK03_other||'','香港公司业务情况':a.HK04||'','香港银行账户情况':a.HK05||'','尚未完成或不确定事项':arr(a.HK06),'当前最希望获得的帮助':arr(a.HK07),'其他帮助说明':a.HK07_other||'','在港状态评估结论':r.conclusion,'优先处理与待完善事项':[...new Set(items)],'下一步建议':arr(r.actions),'主营行业提示依据':r.industry||''})}
 const x=await findCustomer(e,phone),old=x?.fields||{},pre=r.type==='pre-hk';await upsertCustomer(e,phone,{...base(a),'用户状态':pre?'暂无香港公司':'已有香港公司','最近评估类型':pre?'赴港评估':'在港状态评估','最近评估时间':Date.now(),'赴港评估次数':Number(old['赴港评估次数']||0)+(pre?1:0),'在港状态评估次数':Number(old['在港状态评估次数']||0)+(pre?0:1)});return saved}
